### ISSUE TITLE
PHP Fatal error on flight tracker

### ISSUE THREAD

**Issue by devpat21** [vanderbilt-redcap/auto-record-generation#14]
Hello i am getting error after installing external module error is as follow:

rror message: Uncaught Exception: No server specified in /var/www/redcap/modules/flight_tracker_v3.6.6/classes/Download.php:402 Stack trace: #0 /var/www/redcap/modules/flight_tracker_v3.6.6/classes/Download.php(368): Vanderbilt\CareerDevLibrary\Download::sendToServer(NULL, Array) #1 /var/www/redcap/modules/flight_tracker_v3.6.6/emailMgmt/add.php(8): Vanderbilt\CareerDevLibrary\Download::metadata(NULL, NULL) #2 /var/www/redcap/redcap_v10.6.21/ExternalModules/index.php(121): require_once('/var/www/redcap...') #3 {main} thrown
File: /var/www/redcap/modules/flight_tracker_v3.6.6/classes/Download.php
Line: 402

what needs to be done.

**Comment by scottjpearson** [comment]
As of version 3.8.0, out later today, this part of the code is deprecated. If you're attempting to input a new survey into Flight Tracker, I recommend just adding one via the traditional route in REDCap's Online Designer. It will automatically show up in any emailing features.

If there are future issues, feel free to leave them on the Flight Tracker module page (link below) or email me directly at scott.j.pearson@vumc.org. Thanks.
https://github.com/vanderbilt-redcap/flight-tracker/
